-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle-free;port=1521;service_name=freepdb1

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;



CREATE TABLE countries (
	country_id char(2) NOT NULL,
	country_name varchar(40),
	region_id bigint
) ;
ALTER TABLE countries ADD PRIMARY KEY (country_id);
ALTER TABLE countries ALTER COLUMN country_id SET NOT NULL;


CREATE TABLE departments (
	department_id smallint NOT NULL,
	department_name varchar(30) NOT NULL,
	manager_id integer,
	location_id smallint
) ;
CREATE INDEX dept_location_ix ON departments (location_id);
ALTER TABLE departments ADD PRIMARY KEY (department_id);
ALTER TABLE departments ALTER COLUMN department_name SET NOT NULL;


CREATE TABLE employees (
	employee_id integer NOT NULL,
	first_name varchar(20),
	last_name varchar(25) NOT NULL,
	email varchar(25) NOT NULL,
	phone_number varchar(20),
	hire_date timestamp(0) NOT NULL,
	job_id varchar(10) NOT NULL,
	salary double precision,
	commission_pct decimal(2,2),
	manager_id integer,
	department_id smallint
) ;
CREATE INDEX emp_department_ix ON employees (department_id);
CREATE INDEX emp_job_ix ON employees (job_id);
CREATE INDEX emp_manager_ix ON employees (manager_id);
CREATE INDEX emp_name_ix ON employees (last_name, first_name);
ALTER TABLE employees ADD UNIQUE (email);
ALTER TABLE employees ADD PRIMARY KEY (employee_id);
ALTER TABLE employees ALTER COLUMN email SET NOT NULL;
ALTER TABLE employees ALTER COLUMN hire_date SET NOT NULL;
ALTER TABLE employees ALTER COLUMN job_id SET NOT NULL;
ALTER TABLE employees ALTER COLUMN last_name SET NOT NULL;
ALTER TABLE employees ADD CONSTRAINT emp_salary_min CHECK (salary > 0);


CREATE TABLE jobs (
	job_id varchar(10) NOT NULL,
	job_title varchar(35) NOT NULL,
	min_salary integer,
	max_salary integer
) ;
ALTER TABLE jobs ADD PRIMARY KEY (job_id);
ALTER TABLE jobs ALTER COLUMN job_title SET NOT NULL;


CREATE TABLE job_history (
	employee_id integer NOT NULL,
	start_date timestamp(0) NOT NULL,
	end_date timestamp(0) NOT NULL,
	job_id varchar(10) NOT NULL,
	department_id smallint
) ;
CREATE INDEX jhist_department_ix ON job_history (department_id);
CREATE INDEX jhist_employee_ix ON job_history (employee_id);
CREATE INDEX jhist_job_ix ON job_history (job_id);
ALTER TABLE job_history ADD PRIMARY KEY (employee_id,start_date);
ALTER TABLE job_history ADD CONSTRAINT jhist_date_interval CHECK (end_date > start_date);
ALTER TABLE job_history ALTER COLUMN employee_id SET NOT NULL;
ALTER TABLE job_history ALTER COLUMN end_date SET NOT NULL;
ALTER TABLE job_history ALTER COLUMN job_id SET NOT NULL;
ALTER TABLE job_history ALTER COLUMN start_date SET NOT NULL;


CREATE TABLE locations (
	location_id smallint NOT NULL,
	street_address varchar(40),
	postal_code varchar(12),
	city varchar(30) NOT NULL,
	state_province varchar(25),
	country_id char(2)
) ;
CREATE INDEX loc_city_ix ON locations (city);
CREATE INDEX loc_country_ix ON locations (country_id);
CREATE INDEX loc_state_province_ix ON locations (state_province);
ALTER TABLE locations ADD PRIMARY KEY (location_id);
ALTER TABLE locations ALTER COLUMN city SET NOT NULL;


CREATE TABLE regions (
	region_id bigint NOT NULL,
	region_name varchar(25)
) ;
ALTER TABLE regions ADD PRIMARY KEY (region_id);
ALTER TABLE regions ALTER COLUMN region_id SET NOT NULL;
ALTER TABLE countries ADD CONSTRAINT countr_reg_fk FOREIGN KEY (region_id) REFERENCES regions(region_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE departments ADD CONSTRAINT dept_loc_fk FOREIGN KEY (location_id) REFERENCES locations(location_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE departments ADD CONSTRAINT dept_mgr_fk FOREIGN KEY (manager_id) REFERENCES employees(employee_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE employees ADD CONSTRAINT emp_dept_fk FOREIGN KEY (department_id) REFERENCES departments(department_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE employees ADD CONSTRAINT emp_job_fk FOREIGN KEY (job_id) REFERENCES jobs(job_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE employees ADD CONSTRAINT emp_manager_fk FOREIGN KEY (manager_id) REFERENCES employees(employee_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE job_history ADD CONSTRAINT jhist_dept_fk FOREIGN KEY (department_id) REFERENCES departments(department_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE job_history ADD CONSTRAINT jhist_emp_fk FOREIGN KEY (employee_id) REFERENCES employees(employee_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE job_history ADD CONSTRAINT jhist_job_fk FOREIGN KEY (job_id) REFERENCES jobs(job_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE locations ADD CONSTRAINT loc_c_id_fk FOREIGN KEY (country_id) REFERENCES countries(country_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
