# Oracle Connection
ORACLE_DSN    dbi:Oracle:host=oracle-free;port=1521;service_name=freepdb1
ORACLE_USER   HR

# Source Schema
SCHEMA        HR

# Target PostgreSQL Version
PG_VERSION    18

# Export Type
TYPE          TRIGGER

# Convert PL/SQL to PL/pgSQL
PLSQL_PGSQL   1

# User Privileges
USER_GRANTS   1
