ORACLE_DSN    dbi:Oracle:host=oracle-free;port=1521;service_name=freepdb1

ORACLE_USER   HR

SCHEMA        HR

PG_VERSION    18

TYPE          COPY

USER_GRANTS   1

DATA_LIMIT    10000

JOBS          2

NO_START_SCN  1
